config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  resources :line_items
  resources :orders
  resources :customers
  resources :provinces

# set up a route for a GET to /wally with a name of wally
# get 'wally', to: 'products#index', as: 'wally'

# root has a name of 'root'
  root to: 'main#welcome'



  #get '/' => 'products#index'

  # HTTP is a protocol where we use verbs to interact with URIs
  # These are the verbs:
  # GET
  # POST
  # PUT
  # PATCH
  # DELETE

end

app/models/province.rb
class Province < ActiveRecord::Base
	has_many :customers
	validates :name, presence: true
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province

  # GET /provinces
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    if @province.save
      redirect_to @province, notice: 'Province was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /provinces/1
  def update
    if @province.update(province_params)
      redirect_to @province, notice: 'Province was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /provinces/1
  def destroy
    @province.destroy
      redirect_to provinces_url, notice: 'Province was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name, :pst, :gst, :hst, :created_at, :updated_at)
    end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pst %><br>
    <%= f.text_field :pst %>
  </div>
  <div class="field">
    <%= f.label :gst %><br>
    <%= f.text_field :gst %>
  </div>
  <div class="field">
    <%= f.label :hst %><br>
    <%= f.text_field :hst %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pst</th>
      <th>Gst</th>
      <th>Hst</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= province.pst %></td>
        <td><%= province.gst %></td>
        <td><%= province.hst %></td>
        <td><%= province.created_at %></td>
        <td><%= province.updated_at %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<p>
  <strong>Pst:</strong>
  <%= @province.pst %>
</p>

<p>
  <strong>Gst:</strong>
  <%= @province.gst %>
</p>

<p>
  <strong>Hst:</strong>
  <%= @province.hst %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @province.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @province.updated_at %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>